#!/bin/bash

GCP_DEFAULT_USER_PROJECT_ID="$1"
GCP_DEFAULT_USER_DATASET="$2"
GCP_DEFAULT_USER_TABLE="$3"

bq rm --table \
  ${GCP_DEFAULT_USER_PROJECT_ID}:${GCP_DEFAULT_USER_DATASET}.${GCP_DEFAULT_USER_TABLE}
